apiVersion: v1
kind: Service
metadata:
  name: access-verifier
  labels:
    app: access-verifier
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: access-verifier
