apiVersion: apps/v1
kind: Deployment
metadata:
  name: access-verifier
  labels:
    app: access-verifier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: access-verifier
  template:
    metadata:
      labels:
        app: access-verifier
    spec:
      containers:
      - name: access-verifier
        image: acrobaticice/access_verifier:0.1
        ports:
        - containerPort: 8080
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        volumeMounts:
          - name: config-volume
            mountPath: /app/config
      volumes:
        - name: config-volume
          configMap:
            name: access-verifier-config