FROM python:3.11-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

COPY access_verifier.py /app/
COPY config.json /app/config/

EXPOSE 8080

CMD ["python", "access_verifier.py"]
