FROM python:3.11-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

COPY client_data_manager.py /app/
COPY config.json /app/config/

EXPOSE 8081

CMD ["python", "client_data_manager.py", "--port=8081"]
